[package]
name = "winnow-tor"
version = "0.1.0"
edition = "2024"
rust-version = "1.97"
license = "MIT"

[lib]
name = "winnow_tor"
crate-type = ["staticlib", "rlib"]

[dependencies]
arti-client = { version = "=0.46.0", default-features = false, features = ["tokio", "rustls", "compression", "onion-service-client", "static-sqlite"] }
tor-rtcompat = { version = "=0.46.0", default-features = false, features = ["tokio", "rustls"] }
tor-socksproto = "=0.46.0"
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "time", "sync", "macros"] }
tokio-util = { version = "0.7", features = ["compat"] }
anyhow = "1"
rustls = { version = "=0.23.44", default-features = false, features = ["ring", "std", "tls12"] }

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "debuginfo"
